substitutions:
  _SERVICE: simple-wordpress-post-feed-app
  _REGION: us-central1
  _IMAGE: gcr.io/$PROJECT_ID/simple-wordpress-post-feed:${SHORT_SHA}

steps:
  # Build the container
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]

  # Push it
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "$_SERVICE",
        "--image", "$_IMAGE",
        "--region", "$_REGION",
        "--platform", "managed",
        "--allow-unauthenticated"
      ]

images:
  - "$_IMAGE"

options:
  logging: CLOUD_LOGGING_ONLY
