# Learn more about configuring your theme app extension at https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started#step-2-configure-your-extension

name = "wordpress-feed-embed"
type = "theme_app_extension"

api_version = "2024-10"
